# Dependencies
kramdown:
  input: GFM
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Robotics: Science and Systems"
tagline:          'A Robotics Conference'
description:      'RSS 2025, June 22, 2025 - June 25, 2025, Los Angeles, California'
url:              "https://roboticsconference.org"
baseurl:          ""
include:          ['_pages']
exclude:          ['README.md', 'LICENSE.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor', 'GRTAGS', 'GPATH', 'GTAGS', 'deploy.sh']
logo:             "/images/RSS2025-logo.png"


author:
  name:           'Jared Strader'
  url:            https://jaredstrader.github.io/

gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:

google_analytics: G-RCJTV6PJZC

collections:
    committees:
       output: true
       permalink: /committees/:path/
       priority: 4
    information:
       output: true
       permalink: /information/:path/
       priority: 3

defaults:
  -
    scope:
      path: ""
    values:
      priority: 0
