# Dependencies
kramdown:
  input: GFM
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Robotics: Science and Systems"
tagline:          'A Robotics Conference'
description:      'RSS 2024, Jul 15, 2024 - Jul 19, 2024, Delft, Netherlands'
# url:              "https://roboticsconference.org"
url:              "https://rss2023.github.io/rss2024"
baseurl:          ""
include:          ['_pages']
exclude:          ['README.md', 'LICENSE.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor', 'GRTAGS', 'GPATH', 'GTAGS', 'deploy.sh']

author:
  name:           'Enrique Coronado'
  url:            https://enriquecoronadozu.github.io/

gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:

google_analytics: G-RCJTV6PJZC

collections:
    attending:
       output: true
       permalink: /attending/:path/
       priority: 1
    program:
       output: true
       permalink: /program/:path/
       priority: 2
    committees:
       output: true
       permalink: /committees/:path/
       priority: 4
    information:
       output: true
       permalink: /information/:path/
       priority: 3

defaults:
  -
    scope:
      path: ""
    values:
      priority: 0
